import scrapy
from scrapy.loader.processors import Compose, MapCompose, Join, TakeFirst
clean_text = Compose(MapCompose(lambda v: v.strip().replace('\r\n', ' ')), Join())
to_int = Compose(TakeFirst(), int)

class Ad(scrapy.Item):
    codigo_propiedad = scrapy.Field(output_processor=clean_text)
    fecha_publicacion = scrapy.Field(output_processor=clean_text)
    cat_1 = scrapy.Field(output_processor=clean_text)
    cat_2 = scrapy.Field(output_processor=clean_text)
    cat_3 = scrapy.Field(output_processor=clean_text)
    region = scrapy.Field(output_processor=clean_text)
    ciudad = scrapy.Field(output_processor=clean_text)
    barrio = scrapy.Field(output_processor=clean_text)
    titulo = scrapy.Field(output_processor=clean_text)
    precio_1_simbolo = scrapy.Field(output_processor=clean_text)
    precio_1_valor = scrapy.Field(output_processor=clean_text)
    precio_2_simbolo = scrapy.Field(output_processor=clean_text)
    precio_2_valor = scrapy.Field(output_processor=clean_text)
    superficie_total = scrapy.Field(output_processor=clean_text)
    superficie_util = scrapy.Field(output_processor=clean_text)
    dormitorios = scrapy.Field(output_processor=to_int)
    banos = scrapy.Field(output_processor=to_int)
    agencia = scrapy.Field(output_processor=clean_text)
    telefonos = scrapy.Field()
    constructora = scrapy.Field(output_processor=clean_text)
    direccion = scrapy.Field(output_processor=clean_text)
    locacion = scrapy.Field(output_processor=clean_text)
    id = scrapy.Field(output_processor=clean_text)
    url = scrapy.Field(output_processor=clean_text)